name:                efv-advent
version:             0.1.0.0
github:              "efvincent/efv.advent.2019.haskell"
license:             BSD3
author:              "Eric Vincent"
maintainer:          "example@example.com"
copyright:           "2019 Eric Vincent"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/efv-advent-2019#readme>

dependencies:
- base >= 4.7 && < 5
- string-qq
- text

library:
  source-dirs: src

executables:
  efv-advent-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - efv-advent

tests:
  efv-advent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - efv-advent
